
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package hoc5;

/** CUP generated class containing symbol constants. */
public class AnalizadorSintacticoSym {
  /* terminals */
  public static final int AND = 21;
  public static final int OpExp = 7;
  public static final int ParDer = 9;
  public static final int NE = 27;
  public static final int LT = 24;
  public static final int CONST_PRED = 17;
  public static final int ELSE = 14;
  public static final int OR = 20;
  public static final int WHILE = 12;
  public static final int NOT = 28;
  public static final int OpProd = 4;
  public static final int OpDiv = 5;
  public static final int IF = 13;
  public static final int GT = 22;
  public static final int LE = 25;
  public static final int NUM = 15;
  public static final int OpAsig = 6;
  public static final int SEMIC = 10;
  public static final int EOF = 0;
  public static final int GE = 23;
  public static final int BLTIN = 18;
  public static final int PRINT = 11;
  public static final int error = 1;
  public static final int EQ = 26;
  public static final int OpSuma = 2;
  public static final int LLAVE_IZQ = 29;
  public static final int OpResta = 3;
  public static final int LLAVE_DER = 30;
  public static final int VAR = 16;
  public static final int UMINUS = 19;
  public static final int ParIzq = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OpSuma",
  "OpResta",
  "OpProd",
  "OpDiv",
  "OpAsig",
  "OpExp",
  "ParIzq",
  "ParDer",
  "SEMIC",
  "PRINT",
  "WHILE",
  "IF",
  "ELSE",
  "NUM",
  "VAR",
  "CONST_PRED",
  "BLTIN",
  "UMINUS",
  "OR",
  "AND",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NE",
  "NOT",
  "LLAVE_IZQ",
  "LLAVE_DER"
  };
}

