
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package hoc3;

/** CUP generated class containing symbol constants. */
public class AnalizadorSintacticoSym {
  /* terminals */
  public static final int OpExp = 7;
  public static final int ParDer = 9;
  public static final int Enter = 10;
  public static final int COT = 20;
  public static final int COS = 13;
  public static final int OpProd = 4;
  public static final int OpDiv = 5;
  public static final int SQRT = 15;
  public static final int LOG = 16;
  public static final int NUM = 11;
  public static final int OpAsig = 6;
  public static final int EOF = 0;
  public static final int LOGG = 17;
  public static final int error = 1;
  public static final int SEN = 12;
  public static final int OpSuma = 2;
  public static final int OpResta = 3;
  public static final int CSC = 19;
  public static final int TAN = 14;
  public static final int VAR = 21;
  public static final int SEC = 18;
  public static final int UMINUS = 22;
  public static final int ParIzq = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OpSuma",
  "OpResta",
  "OpProd",
  "OpDiv",
  "OpAsig",
  "OpExp",
  "ParIzq",
  "ParDer",
  "Enter",
  "NUM",
  "SEN",
  "COS",
  "TAN",
  "SQRT",
  "LOG",
  "LOGG",
  "SEC",
  "CSC",
  "COT",
  "VAR",
  "UMINUS"
  };
}

